### ISSUE TITLE
suggestion to fix logging with log4j2 in "WAR deployment context"

### ISSUE THREAD

**Issue by rvdb** [eXist-db/exist#1040]
The switch from log4j to log4j2 in eXist-3.0.RC1 has broken logging when eXist is deployed as a WAR file in Tomcat. More precisely, no log files are written at all.

I've figured out what needs to be done for fixing this:

- log4j-web.jar should be added to %EXIST_HOME%/lib/core (see the [log4j2 documentation](https://logging.apache.org/log4j/2.x/manual/webapp.html))
- in the log4j2.xml file that is generated under %EXIST_HOME%/webapp/WEB-INF/log4j2.xml, the path to the log directory should be modified in following way: 

&#160;

    <Property name="logs">${log4j:configParentLocation}/webapp/WEB-INF/logs</Property>

should be changed to:

    <Property name="logs">${web:rootDir}/WEB-INF/logs</Property>

In any case, the original `${log4j:configParentLocation}/webapp/WEB-INF/logs` setting (necessary for 'standalone' deployment of eXist) can't be used, since in a "WAR deployment context", log4j2.xml will be located inside WEB-INF already. I originally tried with `${log4j:configParentLocation}/logs`, but that didn't work (see below); that's why I ended up with the `${web:rootDir}` lookup.

Searching for a working directory lookup inside log4j2.xml, I noticed how the `${log4j:configParentLocation}` lookup didn't work when deployed in Tomcat, resulting in errors like:

    ERROR Cannot acces RandomAccessFile java.io.FileNotFoundException: jndi:\localhost\exist-3.0.RC2\WEB-INF\logs\expath-repo.log 
    ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender for element RollingRandomAccessFile. java.lang.reflect.InvocationTargetException
    Caused by: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager$RollingRandomAccessFileManagerFactory$FactoryData]

Even when I built eXist with the JNDI extension enabled, this didn't change these errors. I don't know if this means that something should be changed to the log4j2 configuration if it wants to work with JNDI. I gave up when I noticed how `${web:rootDir}` is resolved correctly in a "WAR deployment context".

**Comment by adamretter** [comment]
@rvdb Thanks I have read through your detailed update. Would an alternative solution be to:

1. Add `log4j-web.jar` to the WAR file when you call `build.sh dist-war`, I guess this should be done around line 105 of `build/scripts/dist.xml`, I guess we could use @dizzzz's `nl.ow.dilemma.ant.fetch.FetchTask` to retrieve it from Maven Central, just like we do for the Apache FOP FO processor in `extensions/modules/build.xml`.

2. We need to modify the `log4j2.xml` file that is placed into the WAR, in fact we already have an XSLT for that in the form of `build/scripts/dist-war-log4j.xsl` which would just need some small modifications.

If you agree, could you send a PR with those changes please?

**Comment by rvdb** [comment]
@adamretter Sure, that definitely sounds like the way to go! Thanks for the pointers for concrete fixes; I think I'm able to figure it out. I have no experience with the GifFlow branching model, however. If I can set it up and get it working, I hope I'll get everything right and wrap it up in a proper PR.

On a side note, do you think the JNDI issue I noticed when trying to get at a working `log4j2.xml` configuration is important? If it should be filed as a different issue, I won't be able to tell more than this specific case in this specific (Tomcat) context. But I thought I should mention it in case it could point Java eyes to possiblly buggy behaviour.

**Comment by adamretter** [comment]
@rvdb, don't worry too much about GitFlow, you can simply create a branch from the `develop` branch, do your work there, and then send a PR from that branch.

Regards, JNDI, I don't see how that is related to the log4j2 config?

**Comment by rvdb** [comment]
@adamretter Ok, fine. Just two concerns regarding the download of the jar file during the build process:

- IIUC, the `fetch` task downloads and extracts files to a specific folder, so I think that has to be done before the War Ant task. Therefore, I'd think the preparatory "webapps" target is the right place, but where should the `log4j-web.jar` file be stored preferably? In a temporary folder inside `webapp/WEB-INF` that's being deleted after the build, or can it be added to `lib/core` (where the other log4j jars live) and stay there after the build?
- The version of `log4j-web.jar` must correspond to the other log4j2 jars that are included in the eXist code tree. Is it OK to do this via a build property (cf. the download links for FOP), or are there other preferred mechanisms to keep the versions in sync?

(Concerning JNDI: apparently the original `${log4j:configParentLocation}` lookup in `log4j2.xml` is being resolved via JNDI to something like `jndi:\localhost\exist-3.0.RC2\WEB-INF\logs\expath-repo.log `, which threw the error reported in my original report and made me think that resolution does not work as it should.)

**Comment by dizzzz** [comment]
re: JNDI ...as far as I remember internally in tomcat, resources are resolved via a JDNI construction, therefore the `jndi:` protocol is (used to be) registered as new protocol handler.  This is actually the reason why our protocol resolver (for `exist://`) does not work.....

**Comment by adamretter** [comment]
@rvdb I added the `${log4j:configParentLocation}` construct to log4j2, it is not resolved via JNDI.

**Comment by rvdb** [comment]
@adamretter Not in eXist's embedded Jetty server, but maybe JNDI is involved in Tomcat. Since the `java.io.FileNotFoundException` error indicates that it ends up being expanded to `jndi:\localhost\` in Tomcat, and that Tomcat doesn't know how to handle it, I thought it might be related to JNDI not functioning properly. But since we have a working alternative for the log4j2 configuration, we probably don't need to bother.

Anyway, I'll propose my fixes as they are, so you can review them. There are probably smarter ways needed to coordinate the version number of the jar download with those already present in the eXist distribution.

**Comment by adamretter** [comment]
@rvdb Any update on this?

**Comment by rvdb** [comment]
@adamretter Sorry, I already considered it fixed after your commit 4441d345cd69c147d51e630df2419047efc9fead which reworked my pull request. I've just tested with a fresh build and can confirm that your commit fixes the logging configuration in a WAR context, thanks! I haven't investigated the JNDI errors further, as I don't know much about it; just wanted to report what I observed. (Note, I'm mostly off-line this week and I might be slow in responding.)
