### ISSUE TITLE
NPE with higher order functions

### ISSUE THREAD

**Issue by peterstadler** [eXist-db/exist#2779]
### What is the problem

In trying to migrate an eXist app currently running on eXist 3.3 to current 4.7 I hit a strange NPE. The actual code is scattered across several modules and functions but I was able to squeeze it into a single reproducible test (yet, the code does not make much sense anymore ;)

The issue might be related to #2577 and/or #2385?

### Describe how to reproduce or add a test

```xquery
xquery version "3.1";

module namespace ct2="http://exist-db.org/xquery/closures/test2";
declare namespace test="http://exist-db.org/xquery/xqsuite";

(: first object :)
declare function ct2:obj1($item as item()*) as map(*) {
    map {
        'name' : 'obj1',
        'check' : function() as xs:boolean {
            matches($item, 'foo')
        },
        'test' : function() { ct2:do-something($item) }
    }
};

(: second object, referencing a function from object1 :)
declare function ct2:obj2($item as item()*) as map(*) {
    map {
        'name' : 'obj2',
        'check' : function() as xs:boolean {
            not(ct2:obj1($item)('check')())
        },
        'test' : function() { ct2:do-something($item) }
    }
};

(: some function calling ct2:name-by-id() :)
(: this is only introduced to catch the NPE and make it more readable :)
declare function ct2:do-something($id as xs:string) as xs:string+ {
    try { ct2:name-by-id($id) } catch * { $err:code cast as xs:string }
};

(: iterate over objects and return their name, if the test passes :)
declare function ct2:name-by-id($id as xs:string) as xs:string+ {
    for $func in $ct2:functions
    return 
        if($func($id)('check')()) then $func($id)('name')
        else ()
};

(: expose objects :)
declare variable $ct2:functions := 
    for $func in inspect:module-functions()
    return 
        if(function-name($func) => starts-with('ct2:obj')) then $func
        else ()
;

(: now following the tests … :)
declare 
    %test:assertEquals('obj1') 
    function ct2:test1() as xs:string {
        ct2:obj1('foo')('test')()
    };

declare 
    %test:assertEquals('obj1') 
    function ct2:test2() as xs:string {
        ct2:obj2('foo')('test')()
    };

declare 
    %test:assertEquals('obj1', 'obj1') 
    function ct2:test3() as xs:string+ {
        ct2:obj1('foo')('test')(),
        ct2:obj2('foo')('test')()
    };
```

#### Test output

```xml
<testsuites>
    <testsuite package="http://exist-db.org/xquery/closures/test2"
        timestamp="2019-06-02T14:29:02.281Z" tests="3" failures="1" errors="0" pending="0"
        time="PT0.011S">
        <testcase name="test1" class="ct2:test1">
            <failure message="assertEquals failed." type="failure-error-code-1">obj1</failure>
            <output>java:java.lang.NullPointerException</output>
        </testcase>
        <testcase name="test2" class="ct2:test2"/>
        <testcase name="test3" class="ct2:test3"/>
    </testsuite>
</testsuites>
```

NB: the single invocation of `ct2:obj1('foo')('test')()` fails (= testcase 1) but the combination with a successful call to `ct2:obj2('foo')('test')()` works (= testcase 3).

### Context information

- eXist Version : 4.7.0
- eXist Build : 201905201236
- Git commit : 64ba51345
- Java 1.8.0_212 IcedTea (OpenJDK 64-Bit Server VM) 
- Operating System : Linux 4.9.125-linuxkit amd64
- running from Docker image stadlerpeter/existdb:4.7

**Comment by adamretter** [comment]
@peterstadler Do you have the stracktrace for the NPE? It could be in exist.log?

**Comment by peterstadler** [comment]
Sorry, in `exist.log` there's only 
```
2019-06-03 16:03:56,484 [qtp1276894402-47] ERROR (XQueryServlet.java [process]:552) - null 
java.lang.NullPointerException: null
```

Here's the full thread dump (for what it's worth):

```
2019-06-03 16:03:57
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode):

"ForkJoinPool.commonPool-worker-1" #81 daemon prio=5 os_prio=31 tid=0x00007fab5c90c000 nid=0x6617 waiting on condition [0x0000700006f85000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007418ff418> (a java.util.concurrent.ForkJoinPool)
	at java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

"qtp1276894402-80" #80 prio=5 os_prio=31 tid=0x00007fab9c016000 nid=0x8a1b waiting on condition [0x0000700006e82000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000079ef23dd8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.reservedWait(ReservedThreadExecutor.java:292)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:357)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp1276894402-79" #79 prio=5 os_prio=31 tid=0x00007fab7d4c2000 nid=0x8b0b waiting on condition [0x0000700006a76000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000741cd5a80> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:392)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.idleJobPoll(QueuedThreadPool.java:656)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$800(QueuedThreadPool.java:46)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:720)
	at java.lang.Thread.run(Thread.java:748)

"qtp1276894402-75" #75 prio=5 os_prio=31 tid=0x00007fab9cef6800 nid=0x9713 runnable [0x0000700006d7f000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000741d3dff0> (a sun.nio.ch.Util$3)
	- locked <0x0000000741d3e000> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000741d3dfa0> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:423)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"Attach Listener" #57 daemon prio=9 os_prio=31 tid=0x00007fab4e9d5000 nid=0x7407 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"qtp1276894402-48" #48 prio=5 os_prio=31 tid=0x00007fab4c3dd800 nid=0x8803 runnable [0x00007000080b8000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000741cd52a0> (a sun.nio.ch.Util$3)
	- locked <0x0000000741cd52b0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000741ae19c0> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:423)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp1276894402-47" #47 prio=5 os_prio=31 tid=0x00007fab7d1cb000 nid=0x6f03 waiting on condition [0x0000700007fb5000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007419b2f70> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.reservedWait(ReservedThreadExecutor.java:292)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:357)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp1276894402-44" #44 prio=5 os_prio=31 tid=0x00007fab7dac7000 nid=0x8c03 runnable [0x0000700007cac000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000741a8d380> (a sun.nio.ch.Util$3)
	- locked <0x0000000741d56210> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000741a8d580> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:423)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"DestroyJavaVM" #39 prio=5 os_prio=31 tid=0x00007fab9cf13000 nid=0x2303 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"qtp1276894402-38" #38 prio=5 os_prio=31 tid=0x00007fab4c2d0800 nid=0x6503 runnable [0x00007000078a0000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000741ccf190> (a sun.nio.ch.Util$3)
	- locked <0x0000000741ccf180> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000741ccef80> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:423)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"Scanner-0" #37 daemon prio=5 os_prio=31 tid=0x00007fab7cb6a800 nid=0x8f03 in Object.wait() [0x000070000779d000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x0000000741dbaa88> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"Scheduler-1154481189" #36 prio=5 os_prio=31 tid=0x00007fab5c236000 nid=0x6303 waiting on condition [0x000070000769a000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000741db9160> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

"AsyncNCSARequestLog@1cf0cacc" #35 prio=5 os_prio=31 tid=0x00007fab5c3c8000 nid=0x6103 waiting on condition [0x0000700007597000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000741c9af80> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at org.eclipse.jetty.util.BlockingArrayQueue.poll(BlockingArrayQueue.java:392)
	at org.eclipse.jetty.server.AsyncNCSARequestLog$WriterThread.run(AsyncNCSARequestLog.java:78)

"org.eclipse.jetty.util.RolloverFileOutputStream" #34 daemon prio=5 os_prio=31 tid=0x00007fab5c8ae800 nid=0x5f03 in Object.wait() [0x0000700007494000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000741ebad20> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x0000000741ebad20> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"qtp1276894402-33" #33 prio=5 os_prio=31 tid=0x00007fab4ca58000 nid=0x9003 runnable [0x0000700007391000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000741a3b978> (a sun.nio.ch.Util$3)
	- locked <0x0000000741a3b968> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000741a3b838> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:423)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.io.ManagedSelector$$Lambda$471/1655627208.run(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp1276894402-32" #32 prio=5 os_prio=31 tid=0x00007fab5c0fc000 nid=0x5d03 runnable [0x000070000728e000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000741a3c098> (a sun.nio.ch.Util$3)
	- locked <0x0000000741a3c088> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000741a3bf58> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:423)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.io.ManagedSelector$$Lambda$471/1655627208.run(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp1276894402-31-acceptor-0@357bc488-ServerConnector@53c6f96d{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}" #31 prio=5 os_prio=31 tid=0x00007fab4d01a000 nid=0x9203 runnable [0x000070000718b000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	- locked <0x0000000741ac5818> (a java.lang.Object)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:385)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:648)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp1276894402-26-acceptor-0@39b626e5-ServerConnector@fe34b86{SSL,[ssl, http/1.1]}{0.0.0.0:8443}" #26 prio=5 os_prio=31 tid=0x00007fab4d022000 nid=0x9903 runnable [0x0000700006c7c000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	- locked <0x0000000741a3c680> (a java.lang.Object)
	at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:385)
	at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:648)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp1276894402-25" #25 prio=5 os_prio=31 tid=0x00007fab4d01c000 nid=0x2607 runnable [0x0000700006b79000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000741a3b258> (a sun.nio.ch.Util$3)
	- locked <0x0000000741a3b248> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000741a3b118> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:423)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.io.ManagedSelector$$Lambda$471/1655627208.run(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"qtp1276894402-24" #24 prio=5 os_prio=31 tid=0x00007fab5c0f5000 nid=0xa90b runnable [0x000070000625e000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000741a3ab38> (a sun.nio.ch.Util$3)
	- locked <0x0000000741a3ab28> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000741a3a9e8> (a sun.nio.ch.KQueueSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:423)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:360)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.io.ManagedSelector$$Lambda$471/1655627208.run(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

"db.exist.blob-store.vacuum" #20 prio=5 os_prio=31 tid=0x00007fab4e110800 nid=0x5803 waiting on condition [0x0000700006973000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000074153a5c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:549)
	at org.exist.storage.blob.BlobStoreImpl$BlobVacuum.run(BlobStoreImpl.java:1631)
	at java.lang.Thread.run(Thread.java:748)

"db.exist.blob-store.persistent-writer" #19 prio=5 os_prio=31 tid=0x00007fab4c7f7000 nid=0x9f03 waiting on condition [0x0000700006870000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000074153a940> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.exist.storage.blob.BlobStoreImpl$PersistentWriter.run(BlobStoreImpl.java:1562)
	at java.lang.Thread.run(Thread.java:748)

"db.exist.scheduler.quartz-scheduler_QuartzSchedulerThread" #17 prio=5 os_prio=31 tid=0x00007fab9cd94800 nid=0xa103 in Object.wait() [0x000070000676d000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:328)
	- locked <0x0000000741614070> (a java.lang.Object)

"db.exist.scheduler.quartz-worker-4" #16 prio=5 os_prio=31 tid=0x00007fab7ce3b000 nid=0xa303 in Object.wait() [0x000070000666a000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x0000000741613448> (a java.lang.Object)

"db.exist.scheduler.quartz-worker-3" #15 prio=5 os_prio=31 tid=0x00007fab7d9c3000 nid=0xa403 in Object.wait() [0x0000700006567000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x0000000741613728> (a java.lang.Object)

"db.exist.scheduler.quartz-worker-2" #14 prio=5 os_prio=31 tid=0x00007fab7ce3a800 nid=0xa603 in Object.wait() [0x0000700006464000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x0000000741613a08> (a java.lang.Object)

"db.exist.scheduler.quartz-worker-1" #13 prio=5 os_prio=31 tid=0x00007fab7ccf7800 nid=0xa703 in Object.wait() [0x0000700006361000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x0000000741613ce8> (a java.lang.Object)

"Service Thread" #9 daemon prio=9 os_prio=31 tid=0x00007fab9c004800 nid=0x4003 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x00007fab9c824800 nid=0x3f03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007fab9c824000 nid=0x3d03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007fab9c823000 nid=0x3b03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007fab7c820000 nid=0x4503 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007fab7c81e800 nid=0x3903 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007fab9c80b000 nid=0x4a03 in Object.wait() [0x0000700005a46000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x0000000740dba858> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007fab9c808000 nid=0x4c03 in Object.wait() [0x0000700005943000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x0000000740e1fbf0> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=31 tid=0x00007fab7c042800 nid=0x3003 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007fab7c80d800 nid=0x1f07 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007fab7c80e000 nid=0x1d03 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007fab7c80e800 nid=0x2b03 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007fab7c80f800 nid=0x5403 runnable 

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007fab7c810000 nid=0x2e03 runnable 

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007fab7c810800 nid=0x5203 runnable 

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007fab7c811000 nid=0x5003 runnable 

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007fab7c005000 nid=0x2f03 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007fab9c000000 nid=0x4203 waiting on condition 

JNI global references: 2124
```

**Comment by adamretter** [comment]
@peterstadler okay thanks (I removed your thread-dump as that doesn't help here).

**Comment by peterstadler** [comment]
This still has the "awaiting response" label. Is there anything more I could/should provide?

**Comment by wolfgangmm** [comment]
@peterstadler somehow I thought I addressed this issue, but maybe it was a different one. I'll retest.

**Comment by peterstadler** [comment]
Just checked myself with a recent eXist 4.7.1 and the error still occurs.

**Comment by line-o** [comment]
Can be reproduced. exist version 5 is affected.

**Comment by peterstadler** [comment]
ping, ping – any updates here?
Needless to say that I'd really love to see this issue fixed for migrating my app to eXist5 …

**Comment by line-o** [comment]
I am pleased to report that this issue has been fixed meanwhile. Tested in version 6.4.0
