### ISSUE TITLE
Windows/shutdown FATAL message (develop)

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/exist#534]
Question: is the FATAL below a problem? (WIn7, Java8, develop)

reproduce:
- run `bin\startup.sh`
- open `dashboard`, open e.g. `eXide` (essential!)
- press `control-c`

message:
```
19 Mar 2015 12:43:53,031 [Thread-4] INFO  (JettyStart.java [lifeCycleStopping]:433) - Jetty server stopping...
2015-03-19 12:43:54,201 FATAL Unable to register shutdown hook because JVM is shutting down.
Terminate batch job (Y/N)? y
```

**Comment by shabanovd** [comment]
it is, because db will not have shut down procedure for sure.

**Comment by jensopetersen** [comment]
happens on OS X, Java 8, develop as well.

19 Mar 2015 15:54:58,676 [Thread-4] INFO  (JettyStart.java [lifeCycleStopping]:433) - Jetty server stopping...
2015-03-19 15:54:59,782 FATAL Unable to register shutdown hook because JVM is shutting down.

**Comment by shabanovd** [comment]
here some that should help to fix http://stackoverflow.com/questions/17400136/how-to-log-within-shutdown-hooks-with-log4j2

**Comment by dizzzz** [comment]
Ok, I raised the level of this issue, because it really might be a problem for stability?

**Comment by adamretter** [comment]
@dizzzz @jensopetersen I think this might now be fixed in the current HEAD of develop because of the changes in https://github.com/eXist-db/exist/pull/640 and https://github.com/eXist-db/exist/pull/642. Can someone check and verify this independently please?

**Comment by jensopetersen** [comment]
Nope, I still get "FATAL Unable to register shutdown hook because JVM is shutting down." On Mac OS 10.10.3, java version "1.8.0_45", from standard build of fresh zip.

**Comment by dizzzz** [comment]
for me the same; note the change of date format in last line....

```01 Jun 2015 21:48:55,304 [main] INFO  (JettyStart.java [run]:234) - ----------------------------------------------------- 
01 Jun 2015 21:48:55,304 [main] INFO  (JettyStart.java [run]:235) - Server has started on ports 8080 8443. Configured contexts: 
01 Jun 2015 21:48:55,305 [main] INFO  (JettyStart.java [run]:244) - '/exist' 
01 Jun 2015 21:48:55,305 [main] INFO  (JettyStart.java [run]:282) - ----------------------------------------------------- 
^C
01 Jun 2015 21:49:19,082 [Thread-4] INFO  (JettyStart.java [lifeCycleStopping]:433) - Jetty server stopping... 
2015-06-01 21:49:20,257 FATAL Unable to register shutdown hook because JVM is shutting down.
```

**Comment by jensopetersen** [comment]
@adamretter Also, stopping via the Dashboard does not seem possible. Jetty stops, but total shutdown does not happen.

**Comment by adamretter** [comment]
Okay so the issue seems to be with betterForm trying to log some data with log4j during it's shutdown, however log4j is already shutdown which leads to log4j trying to reinitialise itself (add add its shutdown hook) during JVM shutdown which is prohibited.

The error message `FATAL Unable to register shutdown hook because JVM is shutting down.` comes from the following stacktrace (using log4j 2.3 https://github.com/eXist-db/exist/pull/647 and jetty 8.1.17 https://github.com/eXist-db/exist/pull/646) -

```
java.lang.IllegalStateException: Cannot add new shutdown hook as this is not started. Current state: STOPPED
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.addShutdownCallback(DefaultShutdownCallbackRegistry.java:114)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.addShutdownCallback(Log4jContextFactory.java:235)
	at org.apache.logging.log4j.core.LoggerContext.setUpShutdownHook(LoggerContext.java:179)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:140)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:147)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:262)
	at org.apache.log4j.Logger$PrivateManager.getContext(Logger.java:59)
	at org.apache.log4j.Logger.getLogger(Logger.java:37)
	at org.apache.commons.logging.impl.Log4JLogger.getLogger(Log4JLogger.java:262)
	at org.apache.commons.logging.impl.Log4JLogger.<init>(Log4JLogger.java:108)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:545)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:292)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:269)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
	at de.betterform.agent.web.cache.XFSessionCache.<clinit>(XFSessionCache.java:24)
	at de.betterform.agent.web.servlet.BfServletContextListener.contextDestroyed(BfServletContextListener.java:27)
	at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:823)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:160)
	at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:518)
	at org.exist.jetty.WebAppContext.doStop(WebAppContext.java:39)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStop(HandlerCollection.java:250)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStop(HandlerWrapper.java:107)
	at org.eclipse.jetty.server.Server.doStop(Server.java:343)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
	at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:132)
```

Useful links - 

https://logging.apache.org/log4j/2.x/manual/webapp.html#Servlet-3.0
http://stackoverflow.com/questions/17400136/how-to-log-within-shutdown-hooks-with-log4j2

**Comment by jensopetersen** [comment]
@adamretter How can this be a betterform problem when it is possible to shut down eXist cleanly and fully using the Admin Client or the command line?

**Comment by adamretter** [comment]
@jensopetersen The problem only occurs when running in server mode with Jetty, i.e. not when running in embedded mode. It may be that it only occurs on `SIGINT` (e.g. `Ctrl-c`). However the stack trace clearly shows betterForm as the culprit, although it may not be the underlying cause...

**Comment by jensopetersen** [comment]
@adamretter Has SIGINT ever been a recommended method to shut down eXist? I don't see this method described in the documentation or in the book. Are there comparable database systems where one can shut down in this way? It is of course interesting why it is now not possible to cleanly interrupt eXist, but the real bug, in my view, is that it is not possible to shut down via the Dashboard (I have not tried the system tray popup).

**Comment by adamretter** [comment]
@jensopetersen `SIGINT` is equivalent to pressing `Ctrl-c` on the terminal for an interactive process e.g. `$EXIST_HOME/bin/startup.sh`. This is the problem that @dizzzz described and which we are trying to fix. If you cannot shutdown from the Dashboard that is a different issue, I don't want to confuse these, can you open a new issue for that please?

**Comment by jensopetersen** [comment]
@adamretter Yeah, we have all used it, but has this ever been a recommended method?

**Comment by dizzzz** [comment]
Recommended is: press shutdown button on dashboard, monitor log files, and verify that the database is actually shutdown; if the original process still runs, then it is save to press control-c / send sig-int

**Comment by jensopetersen** [comment]
@dizzzz That's the first time I have seen this in print.

**Comment by jensopetersen** [comment]
I have raised the dashboard issue, https://github.com/eXist-db/dashboard/issues/37.

**Comment by dizzzz** [comment]
@jensopetersen It's what @wolfgangmm once told me....

**Comment by adamretter** [comment]
@dizzzz Can you reproduce the issue you filed still?

**Comment by adamretter** [comment]
@jensopetersen @dizzzz Can you still reproduce after @zwobit's fix?

**Comment by zwobit** [comment]
This will "only" fix the "FATAL" message. eXist-db/dashboard#37 seems not to be affected by this commit. :(

**Comment by adamretter** [comment]
@zwobit That's fine, we will deal with the other issue separately

**Comment by dizzzz** [comment]
I'll check

**Comment by dizzzz** [comment]
look god to me !
